version: "3.7"

services:
  proxy:
    image: nginx
    # build:
    #   context: ./nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80

  voting:
    image: ${REGISTRY:-paulopez}/votingapp:${VERSION:-0.1}
    build:
      context: ./src/votingapp
      # dockerfile: ./src/votingapp/Dockerfile
    environment:
      REDIS: mycache:6379

  mycache:
    image: redis

  voting-test:
    image: votingapp-test
    build:
      context: ./test
    environment:
      VOTING_URL: http://proxy:80
