apiVersion: v1
kind: Service
metadata:
  name: votingapp
  namespace: votingapp
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 5000
      nodePort: 30500
  selector:
    app: votingapp
  type: NodePort
