---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - image: nginx
          name: nginx
          volumeMounts:
            - name: config-volume
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: config-volume
          configMap:
            name: nginxconf
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: votingapp
spec:
  ports:
    - nodePort: 30500
      port: 80
      targetPort: 80
  selector:
    app: nginx
  type: NodePort
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconf
  namespace: votingapp
data:
  nginx.conf: |-
    events { worker_connections 1024; }
    http {
        include /etc/nginx/mime.types;
        upstream voting{
            server votingapp;
        }
        server {
            listen 80;
            location / {
                proxy_pass         http://voting/;
                proxy_redirect     off;
                proxy_set_header   Host $host;
                proxy_set_header   X-Real-IP $remote_addr;
                proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header   X-Forwarded-Host $server_name;
            }
            location /ws {
                proxy_pass http://voting/ws;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection "Upgrade";
            }
        }
    }
